[workspace]
resolver = "3"
members = ["crates/blueberry", "crates/blueberry-api", "crates/blueberry-config", "crates/modules"]

[workspace.dependencies]
# errors
thiserror = "2.0.19"
strum = { version = "0.28.0", features = [ "derive" ] }

# common
uuid = { version = "1.24.0", features = [ "v7" ] }
chrono = "0.4.45"
async-trait = "0.1.91"
base64 = "0.23.1"
derive_more = { version = "2.1.1", features = [ "display"] } # mostly for newtype pattern and errors (

# config
serde = { version = "1.0", features = [ "derive" ] }
toml = "0.9"

# cli
clap = { version = "4.5", features = [ "derive" ] }

axum = "0.8.9"
tokio = { version = "1.53.1", features = ["macros", "net", "rt-multi-thread"] }

sqlx = { version = "0.9.0", features = [ "uuid", "chrono", "postgres", "runtime-tokio", "tls-native-tls" ] }
redis = { version = "1.6.0", features = ["tokio-comp", "connection-manager"] }

# tests
testcontainers-modules = { version = "0.15.0", features = [ "postgres", "redis" ] }
mockall = "0.15.0"
