services:
    api:
        container_name: blueberry
        build:
          context: .
        image: blueberry:latest
        environment:
            BLUEBERRY_PROFILE: ${BLUEBERRY_PROFILE:-development}
        ports:
            - "${BLUEBERRY_PORT:-5178}:5178"
        working_dir: /app
        volumes:
            - ./blueberry.toml:/app/blueberry.toml:ro
            - ./blueberry.${BLUEBERRY_PROFILE:-development}.toml:/app/blueberry.${BLUEBERRY_PROFILE:-development}.toml:ro

    db:
        image: postgres:18-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
            POSTGRES_DB: app
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql

volumes:
    postgres-data:
